version: '3.7'

services:
  web_app:
    container_name: checkout_app
    image: lakeside763/checkout-web-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/www
      - /www/node_modules
    command: yarn start
    environment:
      APP_ENV: development
      NEXT_PUBLIC_APP_ENV: development
