version: 2.1

orbs:
  node: circleci/node@4.7

commands:
  run_intall_dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: |
            yarn install
  run_bump_version:
    steps:
      - run:
          name: Bump version
          command: |
            cd ./
            git config --global user.email "lakeside763@gmail.com"
            git config --global user.name "Olalekan Idowu"
            npm version prerelease --preid=alpha

jobs:
  test-app:
    docker:
      - image: cimg/node:12.22.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Check Lint
          command: yarn check-lint
      - run:
          name: Run Component, Unit and Integration testing
          command: yarn test:ci
  bumped-version:
    docker:
      - image: cimg/node:12.22.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'e6:f7:bc:4e:ef:ca:51:cc:76:23:1c:99:5c:b6:41:50'
      - run_bump_version
  build-and-push:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - run:
          name: Build and Tag image
          command: docker-compose build
      - run:
          name: Docker Login
          command: >
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Push image
          command: docker-compose push

workflows:
  checkout_workflow:
    jobs:
      - test-app
      - bumped-version:
          name: bumped-version
          requires:
            - test-app
          filters:
            branches:
              only:
                - develop
              ignore: /.*/
      - build-and-push:
          name: build-and-push
          requires:
            - test-app
            - bumped-version
          filters:
            branches:
              only:
                - develop
              ignore: /.*/
