version: 2.1

orbs:
  node: circleci/node@4.7

commands:
  run_intall_dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: |
            yarn install
  run_bump_version:
    steps:
      - run:
          name: Bump version
          command: |
            git config --global user.email "lakeside763@gmail.com"
            git config --global user.name "Olalekan Idowu"
            npm version prerelease --preid=alpha
            git add -A && git commit -m"ci: bumped version number [ci skip]" && git push

jobs:
  test-app:
    docker:
      - image: cimg/node:16.22.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          commnd: yarn install
      - run:
          name: Run Check Lint
          command: yarn check-lint
      - run:
          name: Run Component, Unit and Integration testing
          command: yarn test:ci
  bumped-version:
    docker:
    - image: cimg/node:16.22.8-stretch
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e5:1a:95:3f:5b:71:d4:74:ce:1a:5e:26:02:f9:30:80"
      - run_bump_version
  build-and-push:
    docker:
    - image: circleci/buildpack-deps
    steps:
        - checkout
        - run:
            name: Build and Tag image
            command: docker-compose build
        - run:
            name: Docker Login
            command: >
              echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - run:
            name: Push image
            command: docker-compose push



workflows:
  sample:
    jobs:
      - test-app
      - bumped-version:
          name: bumped-version
          requires:
            - test-app
          filters:
            branches:
              only:
                - develop
              ignore: /.*/
      - build-and-push:
          name: build-and-push
          requires:
            - test-app
            - bumped-version
          filters:
            branches:
              only:
                - develop
              ignore: /.*/
