#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling, testing and building your project before committing'

# check tsconfig standards
# yarn check-types ||
# (
#   echo 'Failed type checked, make the changes required above';
#   false;
# )

# Check Eslint Standards
yarn check-lint ||
(
  echo 'Eslint Check Failed, make the necessary changes';
  false;
)

# Prettier format
# yarn format ||
# (
#   echo 'Prettier style formatting';
#   true;
# )


# # Check Prettier Standards
# yarn check-format ||
# (
#   echo 'Your styling looks disgusting, Prettier Check Failed, Run yarn format';
#   true;
# )



# If everything passes, you can go ahead and run build
echo 'Code looks good.'


npm test
